cluster.name: "es-minecraft-cluster"
node.name: "elasticsearch1" # Update for each node
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
network.host: 0.0.0.0
http.port: 9200
discovery.seed_hosts: ["elasticsearch2", "elasticsearch3"] # Update for each node
cluster.initial_master_nodes: ["elasticsearch1", "elasticsearch2", "elasticsearch3"]
xpack.security.enabled: false # Set to true when you have proper certificates and are ready to enable security
# xpack.security.transport.ssl.enabled: true
# xpack.security.transport.ssl.verification_mode: certificate
# xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elasticsearch.p12
# xpack.security.transport.ssl.keystore.password: ${ES_KEYSTORE_PASSWORD}
# xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elasticsearch.p12
# xpack.security.transport.ssl.truststore.password: ${ES_TRUSTSTORE_PASSWORD}
# xpack.security.http.ssl.enabled: true
# xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elasticsearch.p12
# xpack.security.http.ssl.keystore.password: ${ES_KEYSTORE_PASSWORD}
# xpack.security.http.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elasticsearch.p12
# xpack.security.http.ssl.truststore.password: ${ES_TRUSTSTORE_PASSWORD}
