redis:
  host: "localhost"
  port: 6379
  db: 0

scaling:
  max_servers: 10
  min_servers: 0

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
  file: "app.log"

# AWS (Optional - Fill in your details later)
# aws:
#   region: "your-aws-region"
#   access_key_id: "YOUR_ACCESS_KEY_ID" # Do NOT store in config, use environment variables
#   secret_access_key: "YOUR_SECRET_ACCESS_KEY" # Do NOT store in config, use environment variables
