version: '3.8'

services:
  bungeecord:
    image: itzg/bungeecord:1.20.2
    container_name: bungeecord-proxy
    ports:
      - "25565:25565"
    environment:
      BUNGEE_VERSION: "1.20.2"
    volumes:
      - ./bungee:/server
    networks:
      - mc-network

  lobby:
    image: itzg/minecraft-server:2023.10.0
    container_name: lobby-server
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.20.1"
      MEMORY: "2G"
    volumes:
      - ./lobby:/data
    networks:
      - mc-network

  minigame1:
    image: itzg/minecraft-server:2023.10.0
    container_name: minigame1-server
    ports:
      - "25567:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.20.1"
      MEMORY: "2G"
    volumes:
      - ./minigame1:/data
    networks:
      - mc-network

  mysql:
    image: mysql:8.0.34
    container_name: mc-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: minecraft
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mc-network

  redis:
    image: redis:7.0.12-alpine
    container_name: mc-redis
    networks:
      - mc-network
    volumes:
      - redis-data:/data

networks:
  mc-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
