version: '3.7'

services:
  grafana:
    image: grafana/grafana:{{ grafana_version }}
    container_name: grafana
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring_net
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}" # Change this! Use Ansible Vault
    depends_on:
      - prometheus
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

volumes:
  grafana_data:

networks:
  monitoring_net:
    external: true
