version: '3.7'

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "25565:25565"
      - "1936:1936"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - mc_net
    restart: always

networks:
  mc_net:
    external: true
