---
- name: Install Docker Compose if not present
  apt:
    name: docker-compose-plugin
    state: present
  when: ansible_os_family == 'Debian' # Adjust for other OS families if needed

- name: Create HAProxy directory
  file:
    path: "{{ haproxy_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create HAProxy certs directory
  file:
    path: /etc/haproxy/certs
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy HAProxy certificate and key
  copy:
    src: "files/certs/{{ haproxy_cert_name }}"
    dest: "/etc/haproxy/certs/{{ haproxy_cert_name }}"
    owner: root
    group: root
    mode: 0600
  no_log: true
  when: haproxy_ssl_enabled | bool

- name: Template HAProxy Docker Compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ haproxy_directory }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644

- name: Template HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_directory }}/haproxy.cfg"
    owner: root
    group: root
    mode: 0644
  notify: restart haproxy

- name: Create systemd Service File for HAProxy
  template:
    src: haproxy.service.j2
    dest: /etc/systemd/system/haproxy.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart haproxy

- name: Enable and Start HAProxy systemd Service
  systemd:
    name: haproxy
    daemon_reload: yes
    enabled: yes
    state: started

- meta: flush_handlers
