---
# System Configuration
timezone: "UTC"

# Elasticsearch Variables
es_version: "7.17.0" # Use a specific, tested version
es_heap_size: "1g" #  Adjust based on your server resources
es_data_dir: "/var/lib/elasticsearch"
es_config_dir: "/etc/elasticsearch"
es_network_host: "0.0.0.0"
es_http_port: 9200
es_security_enabled: true
es_xpack_security_transport_ssl_enabled: true
es_xpack_security_transport_ssl_verification_mode: "certificate"
es_xpack_security_transport_ssl_keystore_path: "{{ es_config_dir }}/certs/elasticsearch.p12"
es_xpack_security_transport_ssl_truststore_path: "{{ es_config_dir }}/certs/elasticsearch.p12"
es_xpack_security_http_ssl_enabled: true
es_xpack_security_http_ssl_keystore_path: "{{ es_config_dir }}/certs/elasticsearch.p12"
es_xpack_security_http_ssl_truststore_path: "{{ es_config_dir }}/certs/elasticsearch.p12"

# Keystore and certificate paths and passwords
es_keystore_password: "your_strong_keystore_password"
es_xpack_security_http_ssl_key_password: "your_http_ssl_key_password"
es_xpack_security_transport_ssl_key_password: "your_transport_ssl_key_password"
es_xpack_security_transport_ssl_keystore_password: "your_transport_ssl_keystore_password"
es_xpack_security_transport_ssl_truststore_password: "your_transport_ssl_truststore_password"
es_xpack_security_http_ssl_keystore_password: "your_http_ssl_keystore_password"
es_xpack_security_http_ssl_truststore_password: "your_http_ssl_truststore_password"

# Logstash Variables
ls_version: "7.17.0" # Use a specific, tested version
ls_heap_size: "500m"
ls_config_dir: "/etc/logstash"
ls_pipeline_workers: 2 # Adjust based on your server resources and testing
logstash_beats_ssl_enabled: true
logstash_password: "your_logstash_password"

# Kibana Variables
kibana_version: "7.17.0" # Use a specific, tested version
kibana_security_enabled: true
kibana_password: "your_kibana_password"

# Filebeat Variables
filebeat_version: "7.17.0" # Use a specific, tested version
filebeat_logstash_ssl_enabled: true

# HAProxy Variables
haproxy_stats_user: "admin"
haproxy_stats_password: "your_strong_haproxy_stats_password" # Use Ansible Vault!
haproxy_stats_port: 1936

# Keepalived Variables (Optional - For HAProxy failover)
keepalived_virtual_ip: "192.168.1.100"  # Example - use an unused IP in your network
keepalived_interface: "eth0"  # Example - adjust to your network interface

# Minecraft Server Variables
minecraft_version: "1.19.4" #  Update with your desired version
minecraft_server_jar_url: "https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar" #  Update with the correct URL
minecraft_server_type: "VANILLA"  # Or PAPER, SPIGOT, etc.
minecraft_server_directory: "/opt/minecraft"
minecraft_user: "minecraft"
minecraft_heap_size: "4G"
minecraft_max_players: 20
minecraft_motd: "A Highly Available Minecraft Server"
rcon_password: "your_strong_rcon_password" # Use Ansible Vault!
online_mode: "true" # Set to false if you want to allow non-premium users

# Backup Variables (using Restic)
backup_enabled: true
backup_location: "/mnt/backup/minecraft"  # Or s3://your-bucket-name for cloud storage
restic_password: "your_strong_restic_password" # Use Ansible Vault!
restic_repository: "{{ backup_location }}"

# Monitoring Variables (Prometheus and Grafana)
prometheus_version: "2.45.0"
grafana_version: "9.5.2"
node_exporter_version: "1.5.0"
haproxy_exporter_version: "0.15.0" # Check for the latest version
grafana_admin_password: "your_grafana_admin_password"
