---
# System Configuration
timezone: "UTC"

# Elasticsearch Variables
es_version: "7.17.0"
es_heap_size: "1g"
es_data_dir: "/var/lib/elasticsearch"
es_config_dir: "/etc/elasticsearch"
es_network_host: "0.0.0.0"
es_http_port: 9200
es_security_enabled: true
es_xpack_security_transport_ssl_enabled: true
es_xpack_security_transport_ssl_verification_mode: "certificate"
es_xpack_security_transport_ssl_keystore_path: "/etc/elasticsearch/certs/elasticsearch.p12"
es_xpack_security_transport_ssl_truststore_path: "/etc/elasticsearch/certs/elasticsearch.p12"
es_xpack_security_http_ssl_enabled: true
es_xpack_security_http_ssl_keystore_path: "/etc/elasticsearch/certs/elasticsearch.p12"
es_xpack_security_http_ssl_truststore_path: "/etc/elasticsearch/certs/elasticsearch.p12"
es_keystore_password: "{{ vault_es_keystore_password }}"  # Encrypted with Ansible Vault

# Logstash Variables
ls_version: "7.17.0"
ls_heap_size: "500m"
ls_config_dir: "/etc/logstash"
ls_pipeline_workers: 2
logstash_beats_ssl_enabled: true
logstash_password: "{{ vault_logstash_password }}" # Encrypted with Ansible Vault

# Kibana Variables
kibana_version: "7.17.0"
kibana_security_enabled: true
kibana_password: "{{ vault_kibana_password }}" # Encrypted with Ansible Vault

# Filebeat Variables
filebeat_version: "7.17.0"
filebeat_logstash_ssl_enabled: true

# HAProxy Variables
haproxy_directory: /opt/haproxy
haproxy_stats_user: "admin"
haproxy_stats_password: "{{ vault_haproxy_stats_password }}" # Encrypted with Ansible Vault
haproxy_stats_port: 1936
haproxy_ssl_enabled: true
haproxy_cert_name: "minecraft.pem" # Your certificate file name (should contain both cert and key)

# Minecraft Server Variables
minecraft_version: "1.19.4" # Minecraft server version
minecraft_server_jar_url: "https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b72558255558e/server.jar" # Update with the correct URL for the desired version
minecraft_server_type: "VANILLA" # Or PAPER, SPIGOT, etc.
minecraft_server_directory: "/opt/minecraft"
minecraft_user: "minecraft"
minecraft_server_port: 25565 # Default Minecraft server port
minecraft_heap_size: "4G"  # Adjust based on your server resources
minecraft_max_players: 20
minecraft_motd: "A Minecraft Server Powered by Ansible and Docker"
rcon_enabled: "true"
rcon_port: 25575
rcon_password: "{{ vault_rcon_password }}" # Encrypted with Ansible Vault
online_mode: "true"

# Backup Variables (using Restic)
backup_enabled: true
backup_location: "/mnt/backup/minecraft"  # Or s3://your-bucket-name
restic_password: "{{ vault_restic_password }}" # Encrypted with Ansible Vault
restic_repository: "{{ backup_location }}"
