---
- name: Ensure Minecraft group exists
  group:
    name: "{{ minecraft_user }}"
    state: present
    system: yes

- name: Ensure Minecraft user exists
  user:
    name: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
    create_home: yes
    home: "{{ minecraft_server_directory }}"
    system: yes
    shell: /bin/bash

- name: Create Minecraft Server Directory
  file:
    path: "{{ minecraft_server_directory }}"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
    mode: 0755

- name: Download Minecraft Server
  get_url:
    url: "{{ minecraft_server_jar_url }}"
    dest: "{{ minecraft_server_directory }}/server.jar"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
    mode: 0755
  register: download_result

- name: Copy EULA file
  copy:
    content: "eula=true"
    dest: "{{ minecraft_server_directory }}/eula.txt"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
    mode: 0644

- name: Template server.properties
  template:
    src: server.properties.j2
    dest: "{{ minecraft_server_directory }}/server.properties"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
    mode: 0644
  notify: restart minecraft

- name: Template systemd Service File
  template:
    src: minecraft.service.j2
    dest: /etc/systemd/system/minecraft.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart minecraft

- name: Enable Minecraft systemd Service
  systemd:
    name: minecraft
    enabled: yes
    masked: no

- name: Start Minecraft systemd Service
  systemd:
    name: minecraft
    state: started

- meta: flush_handlers
