apiVersion: networking.k8s.io/v1  
kind: NetworkPolicy  
metadata:  
  name: minecraft-allow-prometheus  
spec:  
  podSelector:  
    matchLabels:  
      app: minecraft  
  ingress:  
  - from:  
    - namespaceSelector:  
        matchLabels:  
          name: monitoring  
    ports:  
    - port: 9090  
