apiVersion: rbac.authorization.k8s.io/v1  
kind: Role  
metadata:  
  name: minecraft-backup-role  
rules:  
- apiGroups: [""]  
  resources: ["pods", "persistentvolumeclaims"]  
  verbs: ["get", "list"]  
