apiVersion: rbac.authorization.k8s.io/v1  
kind: Role  
metadata:  
  name: minecraft-backup-role  
rules:  
- apiGroups: [""]  
  resources: ["pods", "persistentvolumeclaims"]  
  verbs: ["get", "list"]  

---  
apiVersion: rbac.authorization.k8s.io/v1  
kind: RoleBinding  
metadata:  
  name: minecraft-backup-binding  
subjects:  
- kind: ServiceAccount  
  name: default  
roleRef:  
  kind: Role  
  name: minecraft-backup-role  
  apiGroup: rbac.authorization.k8s.io  
