---
# ... (previous tasks)

- name: Create Elasticsearch certs directory
  file:
    path: "{{ es_config_dir }}/certs"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0750

- name: Copy Elasticsearch keystore and truststore
  copy:
    src: "files/certs/{{ item }}"
    dest: "{{ es_config_dir }}/certs/{{ item }}"
    owner: elasticsearch
    group: elasticsearch
    mode: 0600
  with_items:
    - elasticsearch.p12
    - ca.crt
  no_log: true  # Protect sensitive information in logs
  when: es_security_enabled | bool

- name: Template Elasticsearch configuration (with security)
  template:
    src: elasticsearch.yml.j2
    dest: "{{ es_config_dir }}/elasticsearch.yml"
    owner: elasticsearch
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch
  when: es_security_enabled | bool

- name: Wait for Elasticsearch to be ready
  uri:
    url: "https://localhost:{{ es_http_port }}"
    status_code: 200
    retries: 60
    delay: 5
    validate_certs: no  # Initially, we might use self-signed certs
  when: es_security_enabled | bool

- name: Set Logstash password
  uri:
    url: "https://localhost:{{ es_http_port }}/_security/user/logstash_internal/_password"
    method: POST
    user: "elastic"
    password: "{{ es_admin_password }}"
    body: '{ "password": "{{ logstash_password }}" }'
    body_format: json
    status_code: 200
    headers:
      Content-Type: "application/json"
    validate_certs: no
  delegate_to: "{{ groups['elasticsearch_servers'][0] }}"
  run_once: true
  when: es_security_enabled | bool

- name: Set Kibana password
  uri:
    url: "https://localhost:{{ es_http_port }}/_security/user/kibana_user/_password"
    method: POST
    user: "elastic"
    password: "{{ es_admin_password }}"
    body: '{ "password": "{{ kibana_password }}" }'
    body_format: json
    status_code: 200
    headers:
      Content-Type: "application/json"
    validate_certs: no
  delegate_to: "{{ groups['elasticsearch_servers'][0] }}"
  run_once: true
  when: es_security_enabled | bool
