version: '3.7'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:{{ kibana_version }}
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./certs:/etc/kibana/certs
    ports:
      - "5601:5601"
    networks:
      - es_net
    depends_on:
      - elasticsearch1
      - elasticsearch2
      - elasticsearch3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

networks:
  es_net:
    external: true
