version: '3.7'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:{{ kibana_version }}
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - es_net
    depends_on:
      - elasticsearch1
      - elasticsearch2
      - elasticsearch3

networks:
  es_net:
    external: true
