version: '3.7'

services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:{{ es_version }}
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.name=es-minecraft-cluster
      - discovery.seed_hosts=elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms{{ es_heap_size }} -Xmx{{ es_heap_size }}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data1:/usr/share/elasticsearch/data
      - ./elasticsearch1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9201:9200"
    networks:
      - es_net

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:{{ es_version }}
    container_name: elasticsearch2
    environment:
      - node.name=elasticsearch2
      - cluster.name=es-minecraft-cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms{{ es_heap_size }} -Xmx{{ es_heap_size }}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data2:/usr/share/elasticsearch/data
      - ./elasticsearch2/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - es_net

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:{{ es_version }}
    container_name: elasticsearch3
    environment:
      - node.name=elasticsearch3
      - cluster.name=es-minecraft-cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch2
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms{{ es_heap_size }} -Xmx{{ es_heap_size }}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data3:/usr/share/elasticsearch/data
      - ./elasticsearch3/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - es_net

volumes:
  es_data1:
  es_data2:
  es_data3:

networks:
  es_net:
    driver: bridge
