---
- hosts: all
  become: true
  roles:
    - common
  tags:
    - common

- hosts: elasticsearch_servers
  become: true
  roles:
    - elasticsearch
  tags:
    - elasticsearch

- hosts: logstash_servers
  become: true
  roles:
    - logstash
  tags:
    - logstash

- hosts: kibana_servers
  become: true
  roles:
    - kibana
  tags:
    - kibana

- hosts: minecraft_servers
  become: true
  roles:
    - minecraft_server
    - filebeat
    - backup
  tags:
    - minecraft

- hosts: haproxy_servers
  become: true
  roles:
    - haproxy
  tags:
    - haproxy

- hosts: haproxy_servers[0]
  become: true
  roles:
    - keepalived
  tags:
    - keepalived
  when: keepalived_enabled | bool

- hosts: monitoring_servers
  become: true
  roles:
    - monitoring
  tags:
    - monitoring
