---
- name: Ensure Logstash group exists
  group:
    name: logstash
    state: present
    system: yes

- name: Ensure Logstash user exists
  user:
    name: logstash
    group: logstash
    create_home: no
    system: yes
    shell: /usr/sbin/nologin

- name: Create Logstash directories
  file:
    path: "{{ item }}"
    state: directory
    owner: logstash
    group: logstash
    mode: 0755
  with_items:
    - "{{ ls_config_dir }}"
    - /var/log/logstash

- name: Download Logstash Debian package
  get_url:
    url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ ls_version }}-amd64.deb"
    dest: "/tmp/logstash-{{ ls_version }}-amd64.deb"
    mode: 0644

- name: Install Logstash Debian package
  apt:
    deb: "/tmp/logstash-{{ ls_version }}-amd64.deb"
    state: present

- name: Create Logstash certs directory
  file:
    path: /etc/logstash/certs
    state: directory
    owner: logstash
    group: logstash
    mode: 0750

- name: Copy Logstash certificate and key
  copy:
    src: "files/certs/{{ item }}"
    dest: "/etc/logstash/certs/{{ item }}"
    owner: logstash
    group: logstash
    mode: 0600
  with_items:
    - logstash.crt
    - logstash.key
    - ca.crt
  no_log: true
  when: logstash_beats_ssl_enabled | bool

- name: Template Logstash configuration
  template:
    src: logstash.yml.j2
    dest: "{{ ls_config_dir }}/logstash.yml"
    owner: logstash
    group: logstash
    mode: 0660
  notify: restart logstash

- name: Template Logstash pipeline configuration
  template:
    src: logstash.conf.j2
    dest: "{{ ls_config_dir }}/conf.d/logstash.conf"
    owner: logstash
    group: logstash
    mode: 0660
  notify: restart logstash

- name: Enable Logstash service
  systemd:
    name: logstash
    enabled: yes
    masked: no

- name: Start Logstash service
  systemd:
    name: logstash
    state: started

- meta: flush_handlers
