---
- name: Create Filebeat certs directory
  file:
    path: /etc/filebeat/certs
    state: directory
    owner: root
    group: root
    mode: 0750
  when: filebeat_logstash_ssl_enabled | bool

- name: Copy Filebeat certificate and key
  copy:
    src: "files/certs/{{ item }}"
    dest: "/etc/filebeat/certs/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - filebeat.crt
    - filebeat.key
    - ca.crt
  no_log: true
  when: filebeat_logstash_ssl_enabled | bool

- name: Download Filebeat Debian package    dest: "/tmp/filebeat-{{ filebeat_version }}-amd64.deb"
    mode: 0644

- name: Install Filebeat Debian package
  apt:
    deb: "/tmp/filebeat-{{ filebeat_version }}-amd64.deb"
    state: present

- name: Template Filebeat configuration (with security)
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0644
  notify: restart filebeat

- name: Enable Filebeat service
  systemd:
    name: filebeat
    enabled: yes
    masked: no

- name: Start Filebeat service
  systemd:
    name: filebeat
    state: started

- meta: flush_handlers
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-amd64.deb
