---
- name: Ensure Kibana group exists
  group:
    name: kibana
    state: present
    system: yes

- name: Ensure Kibana user exists
  user:
    name: kibana
    group: kibana
    create_home: no
    system: yes
    shell: /usr/sbin/nologin

- name: Create Kibana certs directory
  file:
    path: /etc/kibana/certs
    state: directory
    owner: kibana
    group: kibana
    mode: 0750
  when: kibana_security_enabled | bool

- name: Copy Kibana certificate and key
  copy:
    src: "files/certs/{{ item }}"
    dest: "/etc/kibana/certs/{{ item }}"
    owner: kibana
    group: kibana
    mode: 0600
  with_items:
    - kibana.crt
    - kibana.key
    - ca.crt
  no_log: true
  when: kibana_security_enabled | bool

- name: Download Kibana Debian package
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-amd64.deb"
    dest: "/tmp/kibana-{{ kibana_version }}-amd64.deb"
    mode: 0644

- name: Install Kibana Debian package
  apt:
    deb: "/tmp/kibana-{{ kibana_version }}-amd64.deb"
    state: present

- name: Template Kibana configuration
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: kibana
    group: kibana
    mode: 0660
  notify: restart kibana

- name: Enable Kibana service
  systemd:
    name: kibana
    enabled: yes
    masked: no

- name: Start Kibana service
  systemd:
    name: kibana
    state: started

- meta: flush_handlers
