name: Image Scan  
on: [push]  
jobs:  
  trivy-scan:  
    runs-on: ubuntu-latest  
    steps:  
    - name: Set up Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy
    - name: Update dependencies
      working-directory: ./path/to/go/module # Adjust this path to your Go module directory
      run: |
        go get golang.org/x/crypto@v0.31.0
        go get golang.org/x/net@v0.33.0
    - name: Update Scala dependencies
      run: sbt update # This assumes you have a build tool like sbt or Maven
    - name: Scan image  
      run: |  
        docker pull itzg/minecraft-server  
        trivy image --exit-code 1 --severity HIGH,CRITICAL itzg/minecraft-server
