name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install redis mock

      - name: Debug: Print GITHUB_WORKSPACE # <--- ADD THIS DEBUG STEP
        run: echo "GITHUB_WORKSPACE is: ${{ github.workspace }}"

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Run tests (no AWS)
        working-directory: ${{ github.workspace }}
        env:
          REDIS_HOST: "localhost"
          REDIS_PORT: "6379"
        run: |
          pytest tests/ -v
