jobs:
  # ... other jobs ...

  ansible-role-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role:
          - common
          - elasticsearch
          - logstash
          - kibana
          - filebeat
          - haproxy
          - minecraft_server
          - backup
          - monitoring

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Molecule and dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements-molecule.txt
          pip install docker

      - name: Run Molecule Test for Role ${{ matrix.role }}
        run: molecule test -d docker --role ansible/roles/${{ matrix.role }}  # Changed -c to -d here!
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          TEST_HOST: docker
