name: Security Scan  
on: [push]  

jobs:  
  trivy-scan:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  

      - name: Set up Docker  
        uses: docker/setup-buildx-action@v3  

      - name: Scan image  
        run: |  
          docker pull itzg/minecraft-server:latest  
          # Ignore unfixed CVEs and allow exit code 0  
          trivy image \  
            --severity HIGH,CRITICAL \  
            --ignore-unfixed \  
            --exit-code 0 \  
            --format table \  
            itzg/minecraft-server:latest  

      - name: Upload scan report  
        uses: actions/upload-artifact@v3  
        if: always()  
        with:  
          name: trivy-scan-results  
          path: trivy-report.txt  
